[book]
authors = ["Isaac Marovitz"]
language = "en"
src = "src"
title = "Whisky Documentation"

[preprocessor.alerts]

[preprocessor.template]

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[output.html]
default-theme = "whisky"
preferred-dark-theme = "whisky"
git-repository-url = "https://github.com/Whisky-App/whisky-book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/Whisky-App/whisky-book/edit/main/{path}"
input-404 = "not-found.md"
additional-css = ["last-changed.css"]

[output.html.print]
enable = false

[output.html.fold]
enable = true
